### ISSUE TITLE
Direct sms not working on Android 13

### ISSUE THREAD

**Issue by AbhishekMuknak** [Kajanan02/react-native-send-direct-sms#5]
When I try this package code on Android 13 device message not initiated on messaging app and not send to the receiving device.

**Comment by Kajanan02** [comment]
This package tested Android 13 devices. It's working fine. are you permitting `android.permission.SEND_SMS` In android/app/src/main/AndroidManifest.xml. And also check your mobile balance

**Comment by AbhishekMuknak** [comment]
Yes I am asking permission before sending sms. But message is not received
by receiver and also there message is not generated in my message app inbox
on Android 13 devices it working fine on below Android 13 devices

**Comment by Kajanan02** [comment]
Can you tell what kind of device you are being tested on?

**Comment by Kajanan02** [comment]
As all pertinent details have been addressed, I assume the matter has been resolved, and I will proceed to close this issue

**Comment by Kajanan02** [comment]
As all pertinent details have been addressed, I assume the matter has been resolved, and I will proceed to close this issue
